# Phase 0

Charger la dataset

In [1]:
import pandas as pd
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
print("Forme :", df.shape)
print(df.dtypes)
df.head()

Forme : (7043, 21)
customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

# Phase 1

afficher la fonction

In [3]:
def audit_qualite(df):
    """
    Affiche un rapport de santé du dataset :
    - dimensions ;
    - types des colonnes ;
    - pourcentage de valeurs manquantes ;
    - répartition de la cible Churn.
    """

    # 1. Afficher les dimensions
    print("========== DIMENSIONS ==========")
    print("Forme :", df.shape)
    print("Nombre de lignes :", df.shape[0])
    print("Nombre de colonnes :", df.shape[1])

    # 2. Afficher le type de chaque colonne
    print("\n========== TYPES DES COLONNES ==========")
    print(df.dtypes)

    # 3. Calculer le pourcentage de valeurs manquantes
    print("\n========== VALEURS MANQUANTES ==========")

    taux_manquants = (
        df.isna()                      # cherche les valeurs manquantes
        .mean()                        # calcule leur proportion
        .mul(100)                      # transforme en pourcentage
        .sort_values(ascending=False)  # trie du plus grand au plus petit
    )

    # Compter les colonnes qui possèdent au moins un manque
    nombre_colonnes_manquantes = (taux_manquants > 0).sum()

    print(
        "Manquants détectés :",
        nombre_colonnes_manquantes,
        "colonne(s)"
    )

    print("\nPourcentage de valeurs manquantes par colonne :")
    print(taux_manquants.round(2))

    # 4. Vérifier que la colonne Churn existe
    print("\n========== RÉPARTITION DE CHURN ==========")

    if "Churn" not in df.columns:
        print("Erreur : la colonne Churn est absente.")
        return

    # 5. Compter les Yes et les No
    effectifs = df["Churn"].value_counts(dropna=False)

    # Calculer leurs pourcentages
    pourcentages = (
        df["Churn"]
        .value_counts(normalize=True, dropna=False)
        .mul(100)
    )

    # Afficher chaque classe avec son nombre et son pourcentage
    for valeur, nombre in effectifs.items():

        if valeur == "No":
            nom_classe = "Non"
        elif valeur == "Yes":
            nom_classe = "Oui"
        else:
            nom_classe = str(valeur)

        print(
            f"Churn {nom_classe} : "
            f"{nombre} ({pourcentages[valeur]:.1f}%)"
        )

    # 6. Vérifier si la cible est déséquilibrée
    classe_majoritaire = pourcentages.idxmax()
    pourcentage_majoritaire = pourcentages.max()

    if len(pourcentages) == 1:
        print(
            "\nCas limite détecté : le dataset contient "
            "une seule classe de Churn."
        )

    elif pourcentage_majoritaire >= 70:
        print(
            "\nAttention : la cible est déséquilibrée."
        )
        print(
            f"La classe majoritaire '{classe_majoritaire}' représente "
            f"{pourcentage_majoritaire:.1f}% des données."
        )
        print(
            "L'accuracy seule pourra donc être trompeuse."
        )

    else:
        print("\nLa cible ne présente pas de fort déséquilibre.")

audit_qualite(df)

========== DIMENSIONS ==========
Forme : (7043, 21)
Nombre de lignes : 7043
Nombre de colonnes : 21

========== TYPES DES COLONNES ==========
customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

========== VALEURS MANQUANTES ==========
Manquants détectés : 0 colonne(s)

Pourcentage de valeurs manquantes par colonne :
customerID          0.0
DeviceProtection    0.0
TotalCharges        0.0
MonthlyCharges      0.0
PaymentMethod       0.0
PaperlessBilling    0.0
Contract            0.0
StreamingMovies     0.0
StreamingTV         0.0
TechSupport         0.0
OnlineBackup        0.0
gender              0.0
OnlineSecurity      0.0
InternetService     0.0
MultipleLines       0.0
PhoneService        0.0
tenure              0.0
Dependents          0.0
Partner             0.0
SeniorCitizen       0.0
Churn               0.0
dtype: float64

========== RÉPARTITION DE CHURN ==========
Churn Non : 5174 (73.5%)
Churn Oui : 1869 (26.5%)

Attention : la cible est déséquilibrée.
La classe majoritaire 'No' représente 73.5% des données.
L'accuracy seule pourra donc être trompeuse.

## Les tests

### Test 1 : Cas normal

In [11]:

print("TEST 1 : DATASET COMPLET")


audit_qualite(df)

TEST 1 : DATASET COMPLET
========== DIMENSIONS ==========
Forme : (7043, 21)
Nombre de lignes : 7043
Nombre de colonnes : 21

========== TYPES DES COLONNES ==========
customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

========== VALEURS MANQUANTES ==========
Manquants détectés : 0 colonne(s)

Pourcentage de valeurs manquantes par colonne :
customerID          0.0
DeviceProtection    0.0
TotalCharges        0.0
MonthlyCharges      0.0
PaymentMethod       0.0
PaperlessBilling    0.0
Contract            0.0
StreamingMovies     0.0
StreamingTV         0.0
TechSupport         0.0
OnlineBackup        0.0
gender              0.0
OnlineSecurity      0.0
InternetService     0.0
MultipleLines       0.0
PhoneService        0.0
tenure              0.0
Dependents          0.0
Partner             0.0
SeniorCitizen       0.0
Churn               0.0
dtype: float64

========== RÉPARTITION DE CHURN ==========
Churn Non : 5174 (73.5%)
Churn Oui : 1869 (26.5%)

Attention : la cible est déséquilibrée.
La classe majoritaire 'No' représente 73.5% des données.
L'accuracy seule pourra donc être trompeuse.

### Test : cas limite

In [10]:

print("TEST 2 : UNE SEULE CLASSE")


df_une_classe = df[df["Churn"] == "Yes"].copy()

audit_qualite(df_une_classe)

TEST 2 : UNE SEULE CLASSE
========== DIMENSIONS ==========
Forme : (1869, 21)
Nombre de lignes : 1869
Nombre de colonnes : 21

========== TYPES DES COLONNES ==========
customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

========== VALEURS MANQUANTES ==========
Manquants détectés : 0 colonne(s)

Pourcentage de valeurs manquantes par colonne :
customerID          0.0
DeviceProtection    0.0
TotalCharges        0.0
MonthlyCharges      0.0
PaymentMethod       0.0
PaperlessBilling    0.0
Contract            0.0
StreamingMovies     0.0
StreamingTV         0.0
TechSupport         0.0
OnlineBackup        0.0
gender              0.0
OnlineSecurity      0.0
InternetService     0.0
MultipleLines       0.0
PhoneService        0.0
tenure              0.0
Dependents          0.0
Partner             0.0
SeniorCitizen       0.0
Churn               0.0
dtype: float64

========== RÉPARTITION DE CHURN ==========
Churn Oui : 1869 (100.0%)

Cas limite détecté : le dataset contient une seule classe de Churn.

### Test : CAS ADVERSARIAL

In [9]:

print("TEST 3 : cas adversarial" )

df_adversarial = pd.DataFrame({
    "Churn": ["No"] * 73 + ["Yes"] * 27
})

audit_qualite(df_adversarial)

TEST 3 : cas adversarial
========== DIMENSIONS ==========
Forme : (100, 1)
Nombre de lignes : 100
Nombre de colonnes : 1

========== TYPES DES COLONNES ==========
Churn    object
dtype: object

========== VALEURS MANQUANTES ==========
Manquants détectés : 0 colonne(s)

Pourcentage de valeurs manquantes par colonne :
Churn    0.0
dtype: float64

========== RÉPARTITION DE CHURN ==========
Churn Non : 73 (73.0%)
Churn Oui : 27 (27.0%)

Attention : la cible est déséquilibrée.
La classe majoritaire 'No' représente 73.0% des données.
L'accuracy seule pourra donc être trompeuse.

# Phase 2

### Observer le problème avant de réparer

In [34]:
# Vérification du type de la colonne TotalCharges

print("Type de TotalCharges :", df["TotalCharges"].dtype)

# On compte les valeurs qui contiennent uniquement des espaces
nombre_espaces = (
    df["TotalCharges"]
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

print("Nombre d'espaces cachés :", nombre_espaces)

Type de TotalCharges : float64
Nombre d'espaces cachés : 0

### Créer la fonction de réparation

In [35]:
def reparer_total_charges(df):
    """
    Convertit TotalCharges en numérique et traite les trous révélés.

    La fonction :
    - détecte les espaces cachés ;
    - vérifie les valeurs non numériques ;
    - convertit TotalCharges en float64 ;
    - remplace les valeurs manquantes par la médiane ;
    - renvoie le DataFrame réparé.
    """

    # Vérifier que la colonne existe
    if "TotalCharges" not in df.columns:
        raise ValueError("La colonne TotalCharges est absente.")

    # Faire une copie pour protéger le DataFrame original
    df_repare = df.copy()

    # Transformer temporairement la colonne en texte
    # et enlever les espaces autour des valeurs
    colonne_texte = (
        df_repare["TotalCharges"]
        .astype("string")
        .str.strip()
    )

    # Compter les chaînes vides
    nombre_espaces = colonne_texte.eq("").sum()

    print("Espaces cachés détectés :", nombre_espaces)

    # Remplacer les chaînes vides par de vraies valeurs manquantes
    colonne_texte = colonne_texte.replace("", pd.NA)

    # Tester la conversion en numérique
    # Les valeurs impossibles deviennent NaN
    colonne_numerique = pd.to_numeric(
        colonne_texte,
        errors="coerce"
    )

    # Chercher les valeurs non vides qui n'ont pas pu être converties
    masque_corruption = (
        colonne_texte.notna()
        & colonne_numerique.isna()
    )

    valeurs_corrompues = (
        colonne_texte[masque_corruption]
        .drop_duplicates()
        .tolist()
    )

    # Cas limite : aucune valeur n'est numérique
    if colonne_numerique.notna().sum() == 0:
        raise ValueError(
            "Conversion refusée : la colonne est entièrement non numérique."
        )

    # Refuser les valeurs corrompues comme 29,90
    if len(valeurs_corrompues) > 0:
        raise ValueError(
            "Conversion refusée. Valeurs non numériques détectées : "
            f"{valeurs_corrompues}"
        )

    # Compter les trous apparus après conversion
    nombre_trous = colonne_numerique.isna().sum()

    print("Trous révélés après conversion :", nombre_trous)

    # Calculer la médiane
    mediane = colonne_numerique.median()

    print("Médiane utilisée :", mediane)

    # Remplacer les trous par la médiane
    colonne_numerique = colonne_numerique.fillna(mediane)

    # Enregistrer la colonne réparée en float64
    df_repare["TotalCharges"] = colonne_numerique.astype("float64")

    print("Type après conversion :", df_repare["TotalCharges"].dtype)
    print(
        "Valeurs manquantes restantes :",
        df_repare["TotalCharges"].isna().sum()
    )

    return df_repare

df_repare = reparer_total_charges(df)

Espaces cachés détectés : 0
Trous révélés après conversion : 0
Médiane utilisée : 1397.475
Type après conversion : float64
Valeurs manquantes restantes : 0

### HAPPY PATH : dataset complete

In [36]:
# HAPPY PATH : réparation du vrai dataset

df_repare = reparer_total_charges(df)

print("\nVérifications finales :")
print("Type :", df_repare["TotalCharges"].dtype)
print(
    "Nombre de valeurs manquantes :",
    df_repare["TotalCharges"].isna().sum()
)
print("Dimensions :", df_repare.shape)

assert df_repare["TotalCharges"].dtype == "float64"
assert df_repare["TotalCharges"].isna().sum() == 0
assert df_repare.shape == df.shape

print("\nHappy path validé.")

Espaces cachés détectés : 0
Trous révélés après conversion : 0
Médiane utilisée : 1397.475
Type après conversion : float64
Valeurs manquantes restantes : 0

Vérifications finales :
Type : float64
Nombre de valeurs manquantes : 0
Dimensions : (7043, 21)

Happy path validé.

afficher des valeurs réparés :

In [37]:
df_repare[["TotalCharges"]].head(10)

   TotalCharges
0         29.85
1       1889.50
2        108.15
3       1840.75
4        151.65
5        820.50
6       1949.40
7        301.90
8       3046.05
9       3487.95

### Edge case : colonne entièrement non numérique

In [38]:
# EDGE CASE : colonne contenant uniquement du texte

df_texte = pd.DataFrame({
    "TotalCharges": [
        "bonjour",
        "texte",
        "erreur"
    ]
})

try:
    reparer_total_charges(df_texte)

except ValueError as erreur:
    print("Erreur correctement détectée :")
    print(erreur)

Espaces cachés détectés : 0
Erreur correctement détectée :
Conversion refusée : la colonne est entièrement non numérique.

### Fonction pour détecter une corruption avant conversion

In [39]:
def detecter_corruption_numerique(df, colonne):
    """
    Repère les valeurs non vides qui ne peuvent pas
    être converties en nombres.
    """

    # Vérifier que la colonne existe
    if colonne not in df.columns:
        raise ValueError(f"La colonne {colonne} est absente.")

    # Transformer en texte et retirer les espaces
    colonne_texte = (
        df[colonne]
        .astype("string")
        .str.strip()
    )

    # Remplacer les chaînes vides par des valeurs manquantes
    colonne_texte = colonne_texte.replace("", pd.NA)

    # Tester la conversion sans modifier le DataFrame
    test_conversion = pd.to_numeric(
        colonne_texte,
        errors="coerce"
    )

    # Repérer les valeurs présentes mais impossibles à convertir
    masque_corruption = (
        colonne_texte.notna()
        & test_conversion.isna()
    )

    valeurs_corrompues = (
        colonne_texte[masque_corruption]
        .drop_duplicates()
        .tolist()
    )

    if len(valeurs_corrompues) == 0:
        print(f"Aucune corruption détectée dans {colonne}.")
    else:
        print(
            f"Valeurs corrompues détectées dans {colonne} :",
            valeurs_corrompues
        )

    return valeurs_corrompues


df_repare = reparer_total_charges(df)

Espaces cachés détectés : 0
Trous révélés après conversion : 0
Médiane utilisée : 1397.475
Type après conversion : float64
Valeurs manquantes restantes : 0

### Adversarial : tester 29,90

In [40]:
# ADVERSARIAL 

df_corrompu = pd.DataFrame({
    "MonthlyCharges": [
        "19.90",
        "29,90",
        "49.50"
    ]
})

valeurs_anormales = detecter_corruption_numerique(
    df_corrompu,
    "MonthlyCharges"
)

assert "29,90" in valeurs_anormales

print("Test adversarial validé.")
detecter_corruption_numerique(df, "MonthlyCharges")

Valeurs corrompues détectées dans MonthlyCharges : ['29,90']
Test adversarial validé.
Aucune corruption détectée dans MonthlyCharges.

[]

Conserver le dataset réparé

In [41]:
df = df_repare

print("Le dataset réparé est enregistré dans df.")
print("Forme :", df.shape)
print("Type de TotalCharges :", df["TotalCharges"].dtype)

Le dataset réparé est enregistré dans df.
Forme : (7043, 21)
Type de TotalCharges : float64